language: php
 
php:
  - 5.4
  - 5.5
  - 5.6

before_install:
  - php composer.phar self-update

install:
  - php composer.phar require satooshi/php-coveralls:~0.6@stable 

before_script:
  - php composer.phar install --prefer-source --no-interaction --dev
  - mkdir -p build/logs

script: 
  - php phpunit.phar --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v